### PR TITLE
Add support for inlining whole json, fix tests

### PR DESCRIPTION
**Pull request by ipanasenko**

### CODE REVIEW

**Comment by gkatsev** [comment]
So basically, if you did something like
```js
var foo = require('./foo.json');
```
It would include the entire JSON?
Sounds reasonable to me.

Can you add a test for this?

Thanks!

**Comment by gkatsev** [comment]
Also, I enabled travis on this repo, if you merge/rebase master it should pick it up.

**Comment by ipanasenko** [comment]
Tests are already there, will rebase later

**Comment by gkatsev** [comment]
Oh, I see. Totally missed that `require('config')` part.

**Comment by ipanasenko** [comment]
@gkatsev rebased and pushed

**Comment by gkatsev** [comment]
Awesome, thank @ipanasenko!

**Comment by gkatsev** [comment]
Thanks published as 1.2.0. I also added you as a collaborator on the repo!

**Comment by ipanasenko** [comment]
Thanks!

**Pull request merged**
